package main

import (
	"fmt"
	"os"

	"github.com/idelchi/godyl/internal/commands"
)

// TODO(Idelchi): https://jerrynsh.com/3-easy-ways-to-add-version-flag-in-go/

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

func main() {
	app := commands.NewApp()
	if err := app.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}
