// Code generated by "stringer -type Status -output status_string___generated.go"; DO NOT EDIT.

package tools

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-200]
	_ = x[BadRequest-400]
	_ = x[InternalServerErr-500]
}

const (
	_Status_name_0 = "OK"
	_Status_name_1 = "BadRequest"
	_Status_name_2 = "InternalServerErr"
)

func (i Status) String() string {
	switch {
	case i == 200:
		return _Status_name_0
	case i == 400:
		return _Status_name_1
	case i == 500:
		return _Status_name_2
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
