name: godyl

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
    tags:
      - "*"

jobs:
  test:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
          - macos-14
    runs-on: ${{ matrix.os }}
    env:
      GODYL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
          check-latest: true

      - name: Run tests
        run: go run ./cmd/godyl --show-platform

      - name: Run godyl
        run: go run ./cmd/godyl --log=error

  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
